[user]
email_sender = "REPLACE WITH EMAIL ADDRESS THAT SENDS THE MESSAGE"
sender_password = "REPLACE WITH"
email_receiver = "REPLACE WITH EMAIL ADDRESS THAT RECEIVES THE MESSAGE"
store_id = "REPLACE WITH YOUR LOCAL STORE ID"

#YOU CAN ADD AS MANY ITEMS AS YOU WANT BELOW.
#REMOVE "#" IN FRONT OF ITEM BLOCKS BELOW THAT ARE BEING USED.

[[items]]
name = "REPLACE WITH ITEM NAME"
url = "REPLACE WITH ITEM URL"

#[[items]]
#name = "REPLACE WITH ITEM NAME"
#url = "REPLACE WITH ITEM URL"

#[[items]]
#name = "REPLACE WITH ITEM NAME"
#url = "REPLACE WITH ITEM URL"

#[[items]]
#name = "REPLACE WITH ITEM NAME"
#url = "REPLACE WITH ITEM URL"

#[[items]]
#name = "REPLACE WITH ITEM NAME"
#url = "REPLACE WITH ITEM URL"
