[user]
email_sender = "autogrind02@gmail.com"
password = "wvjbdqjmtsnnkbwf"
email_reciever = "jlapyth@gmail.com"
store_id = "?storeID=051"

[[items]]
name = "Raspberry Pi 4 2gb"
url = "https://www.microcenter.com/product/621439/raspberry-pi-4-model-b-2gb-ddr4"

[[items]]
name = "Raspberry Pi Zero 2 W"
url = "https://www.microcenter.com/product/643085/raspberry-pi-zero-2-w"

#[[items]]
#name = ""
#url = ""

#[[items]]
#name = ""
#url = ""

#[[items]]
#name = ""
#url = ""